if(WIN32)
    set(PLATFORM_NAME "Windows")
    set(LIB_SUFFIX ".lib")
    set(SHARED_LIB_SUFFIX ".dll")
    add_definitions(-D_WIN32)
elseif(APPLE)
    set(PLATFORM_NAME "macOS")
    set(LIB_SUFFIX ".a")
    set(SHARED_LIB_SUFFIX ".dylib")
    add_definitions(-D__APPLE__)
elseif(UNIX)
    set(PLATFORM_NAME "Linux")
    set(LIB_SUFFIX ".a")
    set(SHARED_LIB_SUFFIX ".so")
    add_definitions(-D__linux__)
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    message(STATUS "Compiler: MSVC")
    set(COMPILER_MSVC TRUE)
    set(COMPILER_MSVC_LIKE TRUE)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    # Check if it is clang-cl (MSVC compatible mode)
    if(CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
        message(STATUS "Compiler: Clang-Cl (MSVC-compatible)")
        set(COMPILER_CLANG_CL TRUE)
        set(COMPILER_MSVC_LIKE TRUE)
    else()
        message(STATUS "Compiler: Clang")
        set(COMPILER_CLANG TRUE)
        set(COMPILER_MSVC_LIKE FALSE)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    message(STATUS "Compiler: GCC")
    set(COMPILER_GCC TRUE)
    set(COMPILER_MSVC_LIKE FALSE)
else()
    message(WARNING "Unknown compiler: ${CMAKE_CXX_COMPILER_ID}")
    set(COMPILER_MSVC_LIKE FALSE)
endif()

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(PLATFORM_SUFFIX "x64")
else()
    set(PLATFORM_SUFFIX "x86")
endif()

# Some package exports only provide Debug/Release artifacts.
# Keep RelWithDebInfo and MinSizeRel mapped to Release reliably.
if(NOT CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO)
    set(CMAKE_MAP_IMPORTED_CONFIG_RELWITHDEBINFO "Release")
endif()
if(NOT CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL)
    set(CMAKE_MAP_IMPORTED_CONFIG_MINSIZEREL "Release")
endif()

set(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel" CACHE STRING "" FORCE)
if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the type of build" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "RelWithDebInfo" "MinSizeRel")
endif()

# /ZI Support editing and continue, only x64 or x86, ARM not supported
# Note: The /ZI option is also incompatible with the use of the __LINE__ predefined macro
#if(MSVC)
#    string(REPLACE "/Zi" "/ZI" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
#endif()